using IceKitSentinel.Api.Data;
using IceKitSentinel.Api.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using System.Text;
using IceKitSentinel.Api.Services.PasswordAnalyzer;
using IceKitSentinel.Api.Services.PasswordGenerator;
using IceKitSentinel.Api.Services.Hasher;
using IceKitSentinel.Api.Services.FileIntegrity;
using IceKitSentinel.Api.Services;
using IceKitSentinel.Api.Services.SecurityHeaders;

// Creates the ASP.NET Core application builder.
var builder = WebApplication.CreateBuilder(args);

// Registers IceKitDbContext with the dependency injection container.
// Entity Framework Core uses Npgsql to connect to PostgreSQL.
builder.Services.AddDbContext<IceKitDbContext>(options =>
options.UseNpgsql(
builder.Configuration.GetConnectionString("DefaultConnection")));

// Enables API controllers such as AuthController.
builder.Services.AddControllers();

// Allows the React frontend to communicate with the API.
builder.Services.AddCors(options =>
{
    options.AddPolicy("ReactFrontend", policy =>
    {
        policy
            .WithOrigins("http://localhost:5173")
            .AllowAnyHeader()
            .AllowAnyMethod();
    });
});
// Reads the JWT configuration from appsettings.Development.json.
var jwtKey = builder.Configuration["Jwt:Key"]
    ?? throw new InvalidOperationException(
        "JWT key is not configured.");

var jwtIssuer = builder.Configuration["Jwt:Issuer"]
    ?? throw new InvalidOperationException(
        "JWT issuer is not configured.");

var jwtAudience = builder.Configuration["Jwt:Audience"]
    ?? throw new InvalidOperationException(
        "JWT audience is not configured.");

// Registers JWT authentication.
builder.Services
    .AddAuthentication(
        JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        // Defines how incoming JWT tokens are validated.
        options.TokenValidationParameters =
            new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidIssuer = jwtIssuer,

                ValidateAudience = true,
                ValidAudience = jwtAudience,

                ValidateLifetime = true,

                ValidateIssuerSigningKey = true,
                IssuerSigningKey =
                    new SymmetricSecurityKey(
                        Encoding.UTF8.GetBytes(jwtKey))
            };
    });

// Enables authorization features such as [Authorize].
builder.Services.AddAuthorization();

// Registers PasswordHasher as a service.
// It hashes passwords during registration and verifies them during login.
builder.Services.AddScoped<PasswordHasher<User>>();
//this is a service that analyzes password security and is used in PasswordAnalysisController.
builder.Services.AddScoped<PasswordSecurityService>();
// Registers PasswordGeneratorService so it can be injected into PasswordGeneratorController.
builder.Services.AddScoped<PasswordGeneratorService>();
// this is the service that creates the hash
builder.Services.AddScoped<HashService>();
// Registers FileIntegrityService so it can be injected into FileIntegrityController.
builder.Services.AddScoped<FileIntegrityService>();
// Registers JwtService so it can be injected into AuthController.
builder.Services.AddScoped<JwtService>();
// Registers SecurityHeadersService so it can be injected into SecurityHeadersController.
builder.Services.AddHttpClient<SecurityHeadersService>().ConfigurePrimaryHttpMessageHandler(() =>
        new HttpClientHandler
        {
            AllowAutoRedirect = false
        });
builder.Services.AddScoped<SsrfProtectionService>();
// Adds OpenAPI services for API documentation.
builder.Services.AddOpenApi();

// Builds the application using all configured services.
var app = builder.Build();

// Enables the OpenAPI endpoint only in the Development environment.
if (app.Environment.IsDevelopment())
{
app.MapOpenApi();
}

// Redirects HTTP requests to HTTPS when an HTTPS port is configured.
app.UseHttpsRedirection();
app.UseCors("ReactFrontend");
// Checks the JWT token on incoming requests.
app.UseAuthentication();

// Checks whether the authenticated user is allowed
// to access a protected endpoint.
app.UseAuthorization();

// Temporary weather data generated by the default ASP.NET Core template.
var summaries = new[]
{
"Freezing", "Bracing", "Chilly", "Cool", "Mild",
"Warm", "Balmy", "Hot", "Sweltering", "Scorching"
};

// Temporary endpoint that returns five random weather forecasts.
app.MapGet("/weatherforecast", () =>
{
var forecast = Enumerable.Range(1, 5)
.Select(index =>
new WeatherForecast(
DateOnly.FromDateTime(
DateTime.Now.AddDays(index)),
Random.Shared.Next(-20, 55),
summaries[
Random.Shared.Next(summaries.Length)]
))
.ToArray();


return forecast;

})
.WithName("GetWeatherForecast");

// Maps all controller endpoints.
// This enables:
// POST /api/auth/register
// POST /api/auth/login
app.MapControllers();

// Starts the IceKit Sentinel API.
app.Run();

// Represents one weather forecast.
// This is temporary template code and can be removed later.
record WeatherForecast(
DateOnly Date,
int TemperatureC,
string? Summary)
{
// Converts Celsius to Fahrenheit.
public int TemperatureF =>
32 + (int)(TemperatureC / 0.5556);
}
